package com.paycore.payment;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.Instant;

@Entity
@Table(name = "payments")
public class Payment {

    @Id
    private String id;

    @Column(name = "merchant_id")
    private String merchantId;

    @Column(name = "customer_id")
    private String customerId;

    @Column(name = "payment_method_id")
    private String paymentMethodId;

    /** Minor currency units (paise, cents). Never a floating-point type. */
    private long amount;
    private String currency;

    @Enumerated(EnumType.STRING)
    private PaymentStatus status;

    private String provider;

    /** Generated by PayCore and sent as the processor's idempotency key on every attempt. */
    @Column(name = "processor_reference")
    private String processorReference;

    @Column(name = "provider_payment_id")
    private String providerPaymentId;

    @Column(name = "idempotency_key")
    private String idempotencyKey;

    @Column(name = "attempt_count")
    private int attemptCount;

    @Column(name = "next_retry_at")
    private Instant nextRetryAt;

    @Column(name = "failure_code")
    private String failureCode;

    @Column(name = "failure_message")
    private String failureMessage;

    @Version
    private Long version;

    @Column(name = "created_at")
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    protected Payment() {}

    public Payment(String id, String merchantId, String customerId, String paymentMethodId, long amount,
                   String currency, String provider, String processorReference, String idempotencyKey,
                   Instant now) {
        this.id = id;
        this.merchantId = merchantId;
        this.customerId = customerId;
        this.paymentMethodId = paymentMethodId;
        this.amount = amount;
        this.currency = currency;
        this.provider = provider;
        this.processorReference = processorReference;
        this.idempotencyKey = idempotencyKey;
        this.status = PaymentStatus.CREATED;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /** The only way to change status: illegal moves (e.g. FAILED to SUCCESS) throw. */
    public PaymentStatus transitionTo(PaymentStatus next, Instant now) {
        if (!status.canTransitionTo(next)) {
            throw new InvalidStateTransitionException("Payment", id, status, next);
        }
        PaymentStatus previous = status;
        status = next;
        updatedAt = now;
        return previous;
    }

    public void startAttempt(Instant now, Instant retryAt) {
        attemptCount++;
        nextRetryAt = retryAt;
        updatedAt = now;
    }

    public void recordFailure(String code, String message) {
        failureCode = code;
        failureMessage = message;
    }

    public void clearFailure() {
        failureCode = null;
        failureMessage = null;
    }

    public void succeeded(String providerPaymentId) {
        this.providerPaymentId = providerPaymentId;
        this.nextRetryAt = null;
        clearFailure();
    }

    public void stopRetrying() {
        nextRetryAt = null;
    }

    public void scheduleRetry(Instant at) {
        nextRetryAt = at;
    }

    public String getId() { return id; }
    public String getMerchantId() { return merchantId; }
    public String getCustomerId() { return customerId; }
    public String getPaymentMethodId() { return paymentMethodId; }
    public long getAmount() { return amount; }
    public String getCurrency() { return currency; }
    public PaymentStatus getStatus() { return status; }
    public String getProvider() { return provider; }
    public String getProcessorReference() { return processorReference; }
    public String getProviderPaymentId() { return providerPaymentId; }
    public String getIdempotencyKey() { return idempotencyKey; }
    public int getAttemptCount() { return attemptCount; }
    public Instant getNextRetryAt() { return nextRetryAt; }
    public String getFailureCode() { return failureCode; }
    public String getFailureMessage() { return failureMessage; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
}
